### ISSUE TITLE
Prefer setter functions to reflection

### ISSUE THREAD

**Issue by cmac1000** [AmericanCouncils/kalinka-bundle#10]
test this case:
-  a class uses a custom setter function
- serializer should use the custom setter, not reflection.

Ideally, the serializer metadata stack, and (in the case of deserialization) maybe something like the resolveMetadata method from serializer graphNavigator should give us this information. Does that work, though? In my tests the 'setter' field in propertyMetadata is always blank - this might only work if we use the @Accessor annotation:

http://jmsyst.com/libs/serializer/master/reference/annotations#accessor

**Comment by DavidMikeSimon** [comment]
This seems to have to do with ModelTraits, not kalinka. And anyways we know serializer doesn't care about our petty mortal setters and getters.
